// <auto-generated />
using System;
using MercuriusAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MercuriusAPI.Migrations;

[DbContext(typeof(MercuriusDBContext))]
[Migration("20250521094528_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GameTeam", b =>
            {
                b.Property<int>("GamesId")
                    .HasColumnType("integer");

                b.Property<int>("TeamsId")
                    .HasColumnType("integer");

                b.HasKey("GamesId", "TeamsId");

                b.HasIndex("TeamsId");

                b.ToTable("GameTeam");
            });

        modelBuilder.Entity("MercuriusAPI.Models.LAN.Game", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BracketType")
                    .HasColumnType("integer");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("FinalsFormat")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Format")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Games");
            });

        modelBuilder.Entity("MercuriusAPI.Models.LAN.Match", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BracketType")
                    .HasColumnType("integer");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("GameId")
                    .HasColumnType("integer");

                b.Property<int>("MatchNumber")
                    .HasColumnType("integer");

                b.Property<int>("RoundNumber")
                    .HasColumnType("integer");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Team1Id")
                    .HasColumnType("integer");

                b.Property<int>("Team2Id")
                    .HasColumnType("integer");

                b.Property<int>("WinnerId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("GameId");

                b.HasIndex("Team1Id");

                b.HasIndex("Team2Id");

                b.HasIndex("WinnerId");

                b.ToTable("Matches");
            });

        modelBuilder.Entity("MercuriusAPI.Models.LAN.Player", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Players");
            });

        modelBuilder.Entity("MercuriusAPI.Models.LAN.Team", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Teams");
            });

        modelBuilder.Entity("PlayerTeam", b =>
            {
                b.Property<int>("PlayersId")
                    .HasColumnType("integer");

                b.Property<int>("TeamsId")
                    .HasColumnType("integer");

                b.HasKey("PlayersId", "TeamsId");

                b.HasIndex("TeamsId");

                b.ToTable("PlayerTeam");
            });

        modelBuilder.Entity("GameTeam", b =>
            {
                b.HasOne("MercuriusAPI.Models.LAN.Game", null)
                    .WithMany()
                    .HasForeignKey("GamesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MercuriusAPI.Models.LAN.Team", null)
                    .WithMany()
                    .HasForeignKey("TeamsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("MercuriusAPI.Models.LAN.Match", b =>
            {
                b.HasOne("MercuriusAPI.Models.LAN.Game", "Game")
                    .WithMany("Matches")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MercuriusAPI.Models.LAN.Team", "Team1")
                    .WithMany()
                    .HasForeignKey("Team1Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MercuriusAPI.Models.LAN.Team", "Team2")
                    .WithMany()
                    .HasForeignKey("Team2Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MercuriusAPI.Models.LAN.Team", "Winner")
                    .WithMany()
                    .HasForeignKey("WinnerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Game");

                b.Navigation("Team1");

                b.Navigation("Team2");

                b.Navigation("Winner");
            });

        modelBuilder.Entity("PlayerTeam", b =>
            {
                b.HasOne("MercuriusAPI.Models.LAN.Player", null)
                    .WithMany()
                    .HasForeignKey("PlayersId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MercuriusAPI.Models.LAN.Team", null)
                    .WithMany()
                    .HasForeignKey("TeamsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("MercuriusAPI.Models.LAN.Game", b =>
            {
                b.Navigation("Matches");
            });
#pragma warning restore 612, 618
    }
}
