// <auto-generated />
using System;
using Mercurius.LAN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercurius.LAN.API.Migrations;

[DbContext(typeof(MercuriusDBContext))]
[Migration("20250522140054_UpdateTableStructureToTPT")]
partial class UpdateTableStructureToTPT
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GameParticipant", b =>
            {
                b.Property<int>("GamesId")
                    .HasColumnType("integer");

                b.Property<int>("ParticipantsId")
                    .HasColumnType("integer");

                b.HasKey("GamesId", "ParticipantsId");

                b.HasIndex("ParticipantsId");

                b.ToTable("GameParticipant");
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Game", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BracketType")
                    .HasColumnType("integer");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("FinalsFormat")
                    .HasColumnType("integer");

                b.Property<int>("Format")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("ParticipantType")
                    .HasColumnType("integer");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Games");
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Match", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("BracketType")
                    .HasColumnType("integer");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Format")
                    .HasColumnType("integer");

                b.Property<int>("GameId")
                    .HasColumnType("integer");

                b.Property<bool>("IsLowerBracketMatch")
                    .HasColumnType("boolean");

                b.Property<int>("MatchNumber")
                    .HasColumnType("integer");

                b.Property<int>("Pariticipant1Id")
                    .HasColumnType("integer");

                b.Property<int?>("Participant1Score")
                    .HasColumnType("integer");

                b.Property<int>("Participant2Id")
                    .HasColumnType("integer");

                b.Property<int?>("Participant2Score")
                    .HasColumnType("integer");

                b.Property<int>("ParticipantType")
                    .HasColumnType("integer");

                b.Property<int>("RoundNumber")
                    .HasColumnType("integer");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("WinnerId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("GameId");

                b.HasIndex("Pariticipant1Id");

                b.HasIndex("Participant2Id");

                b.HasIndex("WinnerId");

                b.ToTable("Matches");
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Participant", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.HasKey("Id");

                b.ToTable("Participants");

                b.UseTptMappingStrategy();
            });

        modelBuilder.Entity("PlayerTeam", b =>
            {
                b.Property<int>("PlayersId")
                    .HasColumnType("integer");

                b.Property<int>("TeamsId")
                    .HasColumnType("integer");

                b.HasKey("PlayersId", "TeamsId");

                b.HasIndex("TeamsId");

                b.ToTable("PlayerTeam");
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Player", b =>
            {
                b.HasBaseType("Mercurius.LAN.API.Models.Participant");

                b.Property<string>("DiscordId")
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Firstname")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Lastname")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RiotId")
                    .HasColumnType("text");

                b.Property<string>("SteamId")
                    .HasColumnType("text");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("text");

                b.ToTable("Players");
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
            {
                b.HasBaseType("Mercurius.LAN.API.Models.Participant");

                b.Property<int>("CaptainId")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasIndex("CaptainId");

                b.ToTable("Teams");
            });

        modelBuilder.Entity("GameParticipant", b =>
            {
                b.HasOne("Mercurius.LAN.API.Models.Game", null)
                    .WithMany()
                    .HasForeignKey("GamesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercurius.LAN.API.Models.Participant", null)
                    .WithMany()
                    .HasForeignKey("ParticipantsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Match", b =>
            {
                b.HasOne("Mercurius.LAN.API.Models.Game", "Game")
                    .WithMany("Matches")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercurius.LAN.API.Models.Participant", "Participant1")
                    .WithMany()
                    .HasForeignKey("Pariticipant1Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercurius.LAN.API.Models.Participant", "Participant2")
                    .WithMany()
                    .HasForeignKey("Participant2Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercurius.LAN.API.Models.Participant", "Winner")
                    .WithMany()
                    .HasForeignKey("WinnerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Game");

                b.Navigation("Participant1");

                b.Navigation("Participant2");

                b.Navigation("Winner");
            });

        modelBuilder.Entity("PlayerTeam", b =>
            {
                b.HasOne("Mercurius.LAN.API.Models.Player", null)
                    .WithMany()
                    .HasForeignKey("PlayersId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercurius.LAN.API.Models.Team", null)
                    .WithMany()
                    .HasForeignKey("TeamsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Player", b =>
            {
                b.HasOne("Mercurius.LAN.API.Models.Participant", null)
                    .WithOne()
                    .HasForeignKey("Mercurius.LAN.API.Models.Player", "Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
            {
                b.HasOne("Mercurius.LAN.API.Models.Player", "Captain")
                    .WithMany()
                    .HasForeignKey("CaptainId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercurius.LAN.API.Models.Participant", null)
                    .WithOne()
                    .HasForeignKey("Mercurius.LAN.API.Models.Team", "Id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Captain");
            });

        modelBuilder.Entity("Mercurius.LAN.API.Models.Game", b =>
            {
                b.Navigation("Matches");
            });
#pragma warning restore 612, 618
    }
}

