// <auto-generated />
using Mercurius.LAN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Mercurius.LAN.API.Migrations
{
    [DbContext(typeof(MercuriusDBContext))]
    [Migration("20260612103000_UserIdentityUniqueness")]
    partial class UserIdentityUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
