// <auto-generated />
using System;
using Mercurius.LAN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercurius.LAN.API.Migrations
{
    [DbContext(typeof(MercuriusDBContext))]
    [Migration("20260430120000_RemovePlayerAndParticipantType")]
    partial class RemovePlayerAndParticipantType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameTeam", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameTeam");
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUser");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinalsFormat")
                        .HasColumnType("integer");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipationMode")
                        .HasColumnType("integer");

                    b.Property<string>("RegisterFormUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLowerBracketMatch")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoserNextMatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Participant1IsBYE")
                        .HasColumnType("boolean");

                    b.Property<int?>("Participant1Score")
                        .HasColumnType("integer");

                    b.Property<bool>("Participant2IsBYE")
                        .HasColumnType("boolean");

                    b.Property<int?>("Participant2Score")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipationMode")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TeamLoserId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamParticipant1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamParticipant2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamWinnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserLoserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserParticipant1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("UserParticipant2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("UserWinnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerNextMatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LoserNextMatchId");

                    b.HasIndex("TeamLoserId");

                    b.HasIndex("TeamParticipant1Id");

                    b.HasIndex("TeamParticipant2Id");

                    b.HasIndex("TeamWinnerId");

                    b.HasIndex("UserLoserId");

                    b.HasIndex("UserParticipant1Id");

                    b.HasIndex("UserParticipant2Id");

                    b.HasIndex("UserWinnerId");

                    b.HasIndex("WinnerNextMatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Placement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Placements");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InfoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SponsorTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaptainUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaptainUserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.TeamInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamInvites");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("RiotId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SteamId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlacementTeam", b =>
                {
                    b.Property<int>("PlacementId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("PlacementId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlacementTeam");
                });

            modelBuilder.Entity("PlacementUser", b =>
                {
                    b.Property<int>("PlacementId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlacementId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlacementUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamUser");
                });

            modelBuilder.Entity("GameTeam", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Match", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", "Game")
                        .WithMany("Matches")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Match", "LoserNextMatch")
                        .WithMany()
                        .HasForeignKey("LoserNextMatchId");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamLoser")
                        .WithMany()
                        .HasForeignKey("TeamLoserId");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamParticipant1")
                        .WithMany()
                        .HasForeignKey("TeamParticipant1Id");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamParticipant2")
                        .WithMany()
                        .HasForeignKey("TeamParticipant2Id");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamWinner")
                        .WithMany()
                        .HasForeignKey("TeamWinnerId");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserLoser")
                        .WithMany()
                        .HasForeignKey("UserLoserId");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserParticipant1")
                        .WithMany()
                        .HasForeignKey("UserParticipant1Id");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserParticipant2")
                        .WithMany()
                        .HasForeignKey("UserParticipant2Id");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserWinner")
                        .WithMany()
                        .HasForeignKey("UserWinnerId");

                    b.HasOne("Mercurius.LAN.API.Models.Match", "WinnerNextMatch")
                        .WithMany()
                        .HasForeignKey("WinnerNextMatchId");

                    b.Navigation("Game");

                    b.Navigation("LoserNextMatch");

                    b.Navigation("TeamLoser");

                    b.Navigation("TeamParticipant1");

                    b.Navigation("TeamParticipant2");

                    b.Navigation("TeamWinner");

                    b.Navigation("UserLoser");

                    b.Navigation("UserParticipant1");

                    b.Navigation("UserParticipant2");

                    b.Navigation("UserWinner");

                    b.Navigation("WinnerNextMatch");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Placement", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", "Game")
                        .WithMany("Placements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.User", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.TeamInvite", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Team", "Team")
                        .WithMany("TeamInvites")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlacementTeam", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Placement", null)
                        .WithMany()
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlacementUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Placement", null)
                        .WithMany()
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Game", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
                {
                    b.Navigation("TeamInvites");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
