// <auto-generated />
using System;
using Mercurius.LAN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercurius.LAN.API.Migrations
{
    [DbContext(typeof(MercuriusDBContext))]
    [Migration("20260810182524_BoundTeamInviteMaintenance")]
    partial class BoundTeamInviteMaintenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AverageGameDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("BracketType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinalsFormat")
                        .HasColumnType("integer");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipationMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlannedStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundBreakDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("games", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BracketType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLowerBracketMatch")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LoserNextMatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Participant1IsBYE")
                        .HasColumnType("boolean");

                    b.Property<int?>("Participant1Score")
                        .HasColumnType("integer");

                    b.Property<bool>("Participant2IsBYE")
                        .HasColumnType("boolean");

                    b.Property<int?>("Participant2Score")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipationMode")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TeamLoserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamParticipant1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamParticipant2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamWinnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLoserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserParticipant1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserParticipant2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserWinnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerNextMatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LoserNextMatchId");

                    b.HasIndex("TeamLoserId");

                    b.HasIndex("TeamParticipant1Id");

                    b.HasIndex("TeamParticipant2Id");

                    b.HasIndex("TeamWinnerId");

                    b.HasIndex("UserLoserId");

                    b.HasIndex("UserParticipant1Id");

                    b.HasIndex("UserParticipant2Id");

                    b.HasIndex("UserWinnerId");

                    b.HasIndex("WinnerNextMatchId");

                    b.ToTable("matches", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Placement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("placements", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.PlacementTeam", b =>
                {
                    b.Property<Guid>("PlacementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlacementId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("placement_teams", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.PlacementUser", b =>
                {
                    b.Property<Guid>("PlacementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PlacementId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("placement_users", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.TournamentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegisteredByUsernameAtRegistration")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamCaptainUserIdAtRegistration")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamLogoUrlAtRegistration")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("TeamNameAtRegistration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsernameAtRegistration")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "RegisteredByUserId")
                        .HasDatabaseName("IX_TournamentRegistrations_GameId_RegisteredBy_PendingActive");

                    b.HasIndex("GameId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_TournamentRegistrations_GameId_TeamId_PendingActive")
                        .HasFilter("\"TeamId\" IS NOT NULL");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TournamentRegistrations_GameId_UserId_PendingActive")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.HasIndex("GameId", "Status", "Kind");

                    b.ToTable("tournament_registrations", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.TournamentRegistrationRosterMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConfirmationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameAtRegistration")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamNameAtRegistration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TournamentRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsernameAtRegistration")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TournamentRosterMembers_GameId_UserId_PendingActive");

                    b.HasIndex("TournamentRegistrationId", "ConfirmationStatus");

                    b.HasIndex("GameId", "TeamId", "UserId");

                    b.ToTable("roster_members", "competition");
                });

            modelBuilder.Entity("Mercurius.Modules.Discovery.Domain.SearchDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("normalized_text");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("route");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_version");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<short>("TypeOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("type_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique();

                    b.HasIndex("NormalizedText", "TypeOrder", "EntityId")
                        .HasDatabaseName("IX_search_documents_active_exact_order")
                        .HasFilter("is_deleted = false AND entity_type IN ('user', 'team', 'game')");

                    b.ToTable("search_documents", "discovery");
                });

            modelBuilder.Entity("Mercurius.Modules.Discovery.Domain.SearchIndexRebuildDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("normalized_text");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("route");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_version");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<short>("TypeOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("type_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("search_index_rebuild_documents", "discovery");
                });

            modelBuilder.Entity("Mercurius.Modules.Discovery.Domain.SearchIndexRebuildJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("search_index_rebuild_jobs", "discovery");
                });

            modelBuilder.Entity("Mercurius.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RiotId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SteamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasFilter("\"NormalizedUsername\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Mercurius.Modules.Sponsorship.Domain.GameSponsorPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Headline")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("SponsorId")
                        .HasColumnType("integer");

                    b.Property<string>("SupportLine")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("SponsorId");

                    b.ToTable("game_sponsor_placements", "sponsorship");
                });

            modelBuilder.Entity("Mercurius.Modules.Sponsorship.Domain.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("InfoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SponsorTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sponsors", "sponsorship");
                });

            modelBuilder.Entity("Mercurius.Modules.Teams.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaptainUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaptainUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("teams", "teams");
                });

            modelBuilder.Entity("Mercurius.Modules.Teams.Domain.TeamInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CancelledAt", "Id")
                        .HasDatabaseName("IX_team_invites_cancelled_retention")
                        .HasFilter("\"Status\" = 3");

                    b.HasIndex("ExpiredAt", "Id")
                        .HasDatabaseName("IX_team_invites_expired_retention")
                        .HasFilter("\"Status\" = 4");

                    b.HasIndex("ExpiresAt", "Id")
                        .HasDatabaseName("IX_team_invites_pending_expiration")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("RespondedAt", "Id")
                        .HasDatabaseName("IX_team_invites_responded_retention")
                        .HasFilter("\"Status\" = 1 OR \"Status\" = 2");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TeamInvites_TeamId_UserId_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("TeamId", "Status", "ExpiresAt");

                    b.HasIndex("UserId", "Status", "ExpiresAt");

                    b.ToTable("team_invites", "teams");
                });

            modelBuilder.Entity("Platform.Eventing.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("ConsumerName", "MessageId");

                    b.ToTable("inbox_messages", "platform");
                });

            modelBuilder.Entity("Platform.Eventing.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc");

                    b.ToTable("outbox_messages", "platform");
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("team_members", "teams");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Match", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Game", "Game")
                        .WithMany("Matches")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Competition.Domain.Match", "LoserNextMatch")
                        .WithMany()
                        .HasForeignKey("LoserNextMatchId");

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamLoserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamParticipant1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamParticipant2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamWinnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserLoserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserParticipant1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserParticipant2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserWinnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mercurius.Modules.Competition.Domain.Match", "WinnerNextMatch")
                        .WithMany()
                        .HasForeignKey("WinnerNextMatchId");

                    b.Navigation("Game");

                    b.Navigation("LoserNextMatch");

                    b.Navigation("WinnerNextMatch");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Placement", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Game", "Game")
                        .WithMany("Placements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.PlacementTeam", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Placement", "Placement")
                        .WithMany("Teams")
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Placement");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.PlacementUser", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Placement", "Placement")
                        .WithMany("Users")
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Placement");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.TournamentRegistration", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Game", "Game")
                        .WithMany("TournamentRegistrations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.TournamentRegistrationRosterMember", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mercurius.Modules.Competition.Domain.TournamentRegistration", "TournamentRegistration")
                        .WithMany("RosterMembers")
                        .HasForeignKey("TournamentRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("TournamentRegistration");
                });

            modelBuilder.Entity("Mercurius.Modules.Discovery.Domain.SearchIndexRebuildDocument", b =>
                {
                    b.HasOne("Mercurius.Modules.Discovery.Domain.SearchIndexRebuildJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercurius.Modules.Sponsorship.Domain.GameSponsorPlacement", b =>
                {
                    b.HasOne("Mercurius.Modules.Competition.Domain.Game", null)
                        .WithOne()
                        .HasForeignKey("Mercurius.Modules.Sponsorship.Domain.GameSponsorPlacement", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Sponsorship.Domain.Sponsor", "Sponsor")
                        .WithMany("GameSponsorPlacements")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Mercurius.Modules.Teams.Domain.Team", b =>
                {
                    b.HasOne("Mercurius.Modules.Identity.Domain.User", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainUserId");

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("Mercurius.Modules.Teams.Domain.TeamInvite", b =>
                {
                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", "Team")
                        .WithMany("TeamInvites")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.HasOne("Mercurius.Modules.Teams.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Game", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Placements");

                    b.Navigation("TournamentRegistrations");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.Placement", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mercurius.Modules.Competition.Domain.TournamentRegistration", b =>
                {
                    b.Navigation("RosterMembers");
                });

            modelBuilder.Entity("Mercurius.Modules.Sponsorship.Domain.Sponsor", b =>
                {
                    b.Navigation("GameSponsorPlacements");
                });

            modelBuilder.Entity("Mercurius.Modules.Teams.Domain.Team", b =>
                {
                    b.Navigation("TeamInvites");
                });
#pragma warning restore 612, 618
        }
    }
}
