// <auto-generated />
using System;
using Mercurius.LAN.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercurius.LAN.API.Migrations
{
    [DbContext(typeof(MercuriusDBContext))]
    partial class MercuriusDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameTeam", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("GameId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameTeam");
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUser");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AverageGameDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("BracketType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinalsFormat")
                        .HasColumnType("integer");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipationMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlannedStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegisterFormUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoundBreakDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.GameSponsorPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Headline")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("SponsorId")
                        .HasColumnType("integer");

                    b.Property<string>("SupportLine")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("SponsorId");

                    b.ToTable("GameSponsorPlacements");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BracketType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLowerBracketMatch")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LoserNextMatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Participant1IsBYE")
                        .HasColumnType("boolean");

                    b.Property<int?>("Participant1Score")
                        .HasColumnType("integer");

                    b.Property<bool>("Participant2IsBYE")
                        .HasColumnType("boolean");

                    b.Property<int?>("Participant2Score")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipationMode")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TeamLoserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamParticipant1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamParticipant2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamWinnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLoserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserParticipant1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserParticipant2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserWinnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerNextMatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LoserNextMatchId");

                    b.HasIndex("TeamLoserId");

                    b.HasIndex("TeamParticipant1Id");

                    b.HasIndex("TeamParticipant2Id");

                    b.HasIndex("TeamWinnerId");

                    b.HasIndex("UserLoserId");

                    b.HasIndex("UserParticipant1Id");

                    b.HasIndex("UserParticipant2Id");

                    b.HasIndex("UserWinnerId");

                    b.HasIndex("WinnerNextMatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Placement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Placements");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("InfoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SponsorTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaptainUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaptainUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.TeamInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TeamInvites_TeamId_UserId_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("TeamId", "Status", "ExpiresAt");

                    b.HasIndex("UserId", "Status", "ExpiresAt");

                    b.ToTable("TeamInvites");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RiotId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SteamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasFilter("\"NormalizedUsername\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL AND \"IsDeleted\" = false");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlacementTeam", b =>
                {
                    b.Property<Guid>("PlacementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlacementId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlacementTeam");
                });

            modelBuilder.Entity("PlacementUser", b =>
                {
                    b.Property<Guid>("PlacementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PlacementId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlacementUser");
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamUser");
                });

            modelBuilder.Entity("GameTeam", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.GameSponsorPlacement", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", "Game")
                        .WithOne("SponsorPlacement")
                        .HasForeignKey("Mercurius.LAN.API.Models.GameSponsorPlacement", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Sponsor", "Sponsor")
                        .WithMany("GameSponsorPlacements")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Match", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", "Game")
                        .WithMany("Matches")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Match", "LoserNextMatch")
                        .WithMany()
                        .HasForeignKey("LoserNextMatchId");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamLoser")
                        .WithMany()
                        .HasForeignKey("TeamLoserId");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamParticipant1")
                        .WithMany()
                        .HasForeignKey("TeamParticipant1Id");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamParticipant2")
                        .WithMany()
                        .HasForeignKey("TeamParticipant2Id");

                    b.HasOne("Mercurius.LAN.API.Models.Team", "TeamWinner")
                        .WithMany()
                        .HasForeignKey("TeamWinnerId");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserLoser")
                        .WithMany()
                        .HasForeignKey("UserLoserId");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserParticipant1")
                        .WithMany()
                        .HasForeignKey("UserParticipant1Id");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserParticipant2")
                        .WithMany()
                        .HasForeignKey("UserParticipant2Id");

                    b.HasOne("Mercurius.LAN.API.Models.User", "UserWinner")
                        .WithMany()
                        .HasForeignKey("UserWinnerId");

                    b.HasOne("Mercurius.LAN.API.Models.Match", "WinnerNextMatch")
                        .WithMany()
                        .HasForeignKey("WinnerNextMatchId");

                    b.Navigation("Game");

                    b.Navigation("LoserNextMatch");

                    b.Navigation("TeamLoser");

                    b.Navigation("TeamParticipant1");

                    b.Navigation("TeamParticipant2");

                    b.Navigation("TeamWinner");

                    b.Navigation("UserLoser");

                    b.Navigation("UserParticipant1");

                    b.Navigation("UserParticipant2");

                    b.Navigation("UserWinner");

                    b.Navigation("WinnerNextMatch");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Placement", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Game", "Game")
                        .WithMany("Placements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.User", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainUserId");

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.TeamInvite", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Team", "Team")
                        .WithMany("TeamInvites")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlacementTeam", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Placement", null)
                        .WithMany()
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlacementUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Placement", null)
                        .WithMany()
                        .HasForeignKey("PlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamUser", b =>
                {
                    b.HasOne("Mercurius.LAN.API.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercurius.LAN.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Game", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Placements");

                    b.Navigation("SponsorPlacement");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Sponsor", b =>
                {
                    b.Navigation("GameSponsorPlacements");
                });

            modelBuilder.Entity("Mercurius.LAN.API.Models.Team", b =>
                {
                    b.Navigation("TeamInvites");
                });
#pragma warning restore 612, 618
        }
    }
}
