global using Mercurius.Modules.Identity.Domain;
global using Mercurius.Modules.Teams.Domain;
global using Mercurius.Modules.Tournament.Application;
global using Mercurius.Modules.Tournament.Application.Services;
global using Mercurius.Modules.Tournament.Application.Services.BracketTypes;
global using Mercurius.Modules.Tournament.Domain;
global using TournamentAggregate = Mercurius.Modules.Tournament.Domain.Tournament;
global using TournamentRosterConfirmationChangedEvent = Mercurius.Modules.Tournament.Contracts.TournamentRosterConfirmationChangedEvent;
global using TeamInviteStatus = Mercurius.Modules.Teams.Contracts.TeamInviteStatus;
global using SponsorContext = Mercurius.Modules.Sponsorship.Contracts.SponsorContext;
global using SponsorTier = Mercurius.Modules.Sponsorship.Contracts.SponsorTier;
