<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
     <AssemblyName>Mercurius.LAN.API</AssemblyName>
		<RootNamespace>Mercurius.LAN.API</RootNamespace>
		<UserSecretsId>aspnet-Mercurius.LAN.API-ceac6faf-a2c0-4bdb-a3f1-f7b60c89e1ee</UserSecretsId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
		<NoWarn>CS1591;CS8602;CS8618</NoWarn>
	</PropertyGroup>


	<ItemGroup>
	  <Content Include="staticfiles\swagger-custom.js">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
       <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
		<PackageReference Include="Scrutor" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modules.Shared\Modules.Shared.csproj" />
		<ProjectReference Include="..\Modules\Competition\Mercurius.Modules.Competition\Mercurius.Modules.Competition.csproj" />
		<ProjectReference Include="..\Modules\Discovery\Mercurius.Modules.Discovery\Mercurius.Modules.Discovery.csproj" />
		<ProjectReference Include="..\Modules\Identity\Mercurius.Modules.Identity\Mercurius.Modules.Identity.csproj" />
		<ProjectReference Include="..\Modules\Media\Mercurius.Modules.Media\Mercurius.Modules.Media.csproj" />
		<ProjectReference Include="..\Modules\Sponsorship\Mercurius.Modules.Sponsorship\Mercurius.Modules.Sponsorship.csproj" />
		<ProjectReference Include="..\Modules\Teams\Mercurius.Modules.Teams\Mercurius.Modules.Teams.csproj" />
		<ProjectReference Include="..\Platform\Platform.csproj" />
	</ItemGroup>
</Project>
