<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TestInfrastructure\PostgresTestDatabase.cs" Link="TestInfrastructure\PostgresTestDatabase.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MercuriusAPI\Mercurius.LAN.API.csproj" />
    <ProjectReference Include="..\..\src\Modules\Tournament\Mercurius.Modules.Tournament\Mercurius.Modules.Tournament.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sponsorship\Mercurius.Modules.Sponsorship\Mercurius.Modules.Sponsorship.csproj" />
  </ItemGroup>
</Project>
