<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mercurius.Modules.Sponsorship.Contracts\Mercurius.Modules.Sponsorship.Contracts.csproj" />
    <ProjectReference Include="..\..\Media\Mercurius.Modules.Media.Contracts\Mercurius.Modules.Media.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Modules.Shared\Modules.Shared.csproj" />
    <ProjectReference Include="..\..\..\Platform\Platform.csproj" />
  </ItemGroup>

</Project>
