---
name: Continuous Delivery

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: backend
  DOCKERFILE_PATH: Dockerfile
  CONTEXT_PATH: .

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    name: Calculate SemVersion and Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: images/github-runner
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true

    outputs:
      VERSION: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
      RELEASE_CREATED: ${{ steps.release.outputs.release_created}}

  build-and-push-image:
    runs-on: ubuntu-24.04
    name: Build and Push Docker Image
    needs: release-please
    if: ${{ needs.release-please.outputs.RELEASE_CREATED }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: livingwooods/mercurius-backend:${{ needs.release-please.outputs.VERSION }}
