---
name: Continuous Integration - Application

on:
  pull_request:
    branches:
    - main
    paths: 
    - src/**
    types: 
    - opened
    - synchronize
    - reopened
    - ready_for_review

jobs:
  build:
    runs-on: ubuntu-24.04
    name: "Build Application"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test
